apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z21og7tzr-nodejs 
  janus-idp.io/tekton: z21og7tzr-nodejs
  backstage.io/kubernetes-id: z21og7tzr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z21og7tzr-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  